# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'Upscribe'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'edm_data_transformation'

require-dbt-version: [">=1.0.0", "<2.0.0"]

vars:
  raw_database: "edm-saras" #equivalent to project_id in BigQuery
    # Example Database name
  raw_schema: "EDM_Daton" #equivalent to dataset in BigQuery
    # Example Schema name



  currency_conversion_flag: True
  get_brandname_from_tablename_flag: True
  brandname_position_in_tablename: 0
  # Example- default_brandname: "Nike"
  default_brandname: "" 
  get_storename_from_tablename_flag: True 

  
  storename_position_in_tablename: 1
  # Example- default_storename: "US"
  default_storename: "" 

  UpscribeSubscriptionItems : True
  UpscribeSubscription : True
  UpscribeCustomers : True
  UpscribeOrders : True
  UpscribeOrdersTaxLines : True
  UpscribeRefunds : True
  UpscribeProducts : True
  UpscribeSubscriptionQueues : True
  UpscribeCollections : True

  timezone_conversion_flag : False
  raw_table_timezone_offset_hours: {
    "edm-saras.EDM_Daton.Brand_US_Upscribe_BQ_Customers" : -7,
    "edm-saras.EDM_Daton.Brand_US_Upscribe_BQ_Orders" : -7,
    "edm-saras.EDM_Daton.Brand_US_Upscribe_BQ_Subscriptions" : -7,
    "edm-saras.EDM_Daton.Brand_US_Upscribe_BQ_Refunds"  : -7,
    "edm-saras.EDM_Daton.Brand_US_Upscribe_BQ_SubscriptionQueues" : -7,
    "edm-saras.EDM_Daton.Brand_US_Upscribe_BQ_Products" : -7 
    }
  upscribe_collection_ptrn: '%%upscribe%collections'
  upscribe_collection_tbl_exclude_ptrn: ''
  upscribe_collections_lookback: 2592000000

  upscribe_customers_ptrn: '%upscribe%customers'
  upscribe_customers_tbl_exclude_ptrn: ''
  upscribe_customers_lookback: 2592000000

  upscribe_orders_ptrn: '%upscribe%orders'
  upscribe_orders_tbl_exclude_ptrn: ''
  upscribe_orders_lookback: 2592000000

  upscribe_products_ptrn: '%upscribe%products'
  upscribe_products_tbl_exclude_ptrn: ''
  upscribe_products_lookback: 2592000000

  upscribe_refunds_ptrn: '%upscribe%refunds'
  upscribe_refunds_tbl_exclude_ptrn: ''
  upscribe_refunds_lookback: 2592000000

  upscribe_subscription_ptrn: '%upscribe%subscriptions'
  upscribe_subscription_tbl_exclude_ptrn: ''
  upscribe_subscription_lookback: 2592000000

  upscribe_subscription_queues_ptrn: '%upscribe%subscriptionqueues'
  upscribe_subscription_queues_tbl_exclude_ptrn: ''
  upscribe_subscription_queues_lookback: 2592000000





  
# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:    
  Upscribe:
    +schema: stg_upscribe
